'use client'
import authMiddleware from '@/authMiddleware';
import './globals.css';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import React from 'react';
import { ActionTippy } from '@/components/ActionTippy';
import {MdMenuOpen} from 'react-icons/md';
import Tippy from '@tippyjs/react/headless';
import { Button } from '@/components/Button';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Words List',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const [welcome, setWelcome] = React.useState('');
  const [validate, setValidate] = React.useState(false);

  React.useLayoutEffect(() => {
        const fetchApi = async () => {
            const checkValidate = await authMiddleware();
            if(!checkValidate.error) {
                setValidate(true);
                setWelcome(checkValidate.email);
            } else setValidate(false);
        }
        fetchApi();
  },[]);


  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <div className='navbar_response'>
          <Tippy
              offset={[0,0]}
              placement='bottom-start'
              hideOnClick={true}
              trigger='click'
              interactive={true}
              render={attrs => (
                  <div className="box_menuTippy" tabIndex={-1} {...attrs}>
                      <Button> <Link href='/'> Home </Link></Button>
                      <Button> <Link href='/AddWordPage'>Add your word</Link> </Button>
                      <Button> <Link href='/ListPage'>List all words</Link> </Button>
                  </div>
            )}
          >
            <button className='menu-btn_response'><MdMenuOpen /></button>
          </Tippy>
          {!validate ?
              <div className='account-btn_container'>
                <Button primary small> <Link href='/LoginPage'>Login</Link> </Button>
                <Button secondary small> <Link href='/RegisterPage'>Register</Link> </Button>
              </div> : 
              <ActionTippy>
                <div className='account-user_container'>
                  <img src='/images/avatar.jfif' className='account-avatar' alt='account-avatar' />
                </div>
            </ActionTippy> 
            }
        </div>
        <div className='navbar'>
            <div className='action-btn_container'>
              <Button> <Link href='/'> Home </Link></Button>
              <Button> <Link href='/AddWordPage'>Add your word</Link> </Button>
              <Button> <Link href='/ListPage'>List all words</Link> </Button>
            </div>
            {!validate ?
              <div className='account-btn_container'>
                <Button primary medium > <Link href='/LoginPage'>Login</Link> </Button>
                <Button secondary medium> <Link href='/RegisterPage'>Register</Link> </Button>
              </div> : 
              <ActionTippy>
                <div className='account-user_container'>
                  <div>{`Welcome ${welcome}`}</div>
                  <img src='/images/avatar.jfif' className='account-avatar' alt='account-avatar' />
                </div>
            </ActionTippy> 
            }
        </div>
        {children}
      
      </body>
    </html>
  )
}
